services:
  database:
      build: "db"
      environment:
        - POSTGRES_DB=${DATABASE_DB}
        - POSTGRES_USER=${DATABASE_USERNAME}
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      volumes:
        - db-volume:/var/lib/postgresql/data
      networks: 
        - app-network
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U usr -d db -h localhost"]
        interval: 5s
        timeout: 3s
        retries: 10

  simple-api:
      build: "simple-api"
      environment:
        - DATABASE_URL=jdbc:postgresql://database:5432/${DATABASE_DB}
        - DATABASE_USERNAME=${DATABASE_USERNAME}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        - DATABASE_DB=${DATABASE_DB}
      depends_on:
        - database
      networks:
        - app-network
        - proxy-network

  httpd:
      build: "http-server"
      environment:
        - BACKEND=${BACKEND}
      ports:
        - "80:80"
      depends_on:
        - simple-api
      networks:
        - proxy-network

networks:
  app-network:
  proxy-network:

volumes:
  db-volume:
